config/routes.rb
Archispec::Application.routes.draw do
  

  
  resources :abouts

  resources :videos

  resources :locations

  resources :suppliers

  resources :programs

  resources :speakers

  devise_for :admins

mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' # Feel free to change '/admin' to any namespace you need.
root :to => 'archispec#home' #RAILS 3
  get "archispec/speakers"

  get "archispec/about_us"

  get "archispec/program"

  get "archispec/videos"

  get "archispec/partners"

  get "archispec/location"

  get "archispec/request_invite"

  get "archispec/home"

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :description, :producer_email, :producer_name, :producer_title, :title
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :airpor_namet, :airport_description, :city, :description, :state, :title, :website, :zip
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :title
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  attr_accessible :bio, :name, :organization, :title
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :name
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :title, :vimeo_url
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abouts }
    end
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
    @about = About.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @about }
    end
  end

  # GET /abouts/new
  # GET /abouts/new.json
  def new
    @about = About.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @about }
    end
  end

  # GET /abouts/1/edit
  def edit
    @about = About.find(params[:id])
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(params[:about])

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render json: @about, status: :created, location: @about }
      else
        format.html { render action: "new" }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /abouts/1
  # PUT /abouts/1.json
  def update
    @about = About.find(params[:id])

    respond_to do |format|
      if @about.update_attributes(params[:about])
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about = About.find(params[:id])
    @about.destroy

    respond_to do |format|
      format.html { redirect_to abouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/archispec_helper.rb
module ArchispecHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/speaker_helper.rb
module SpeakerHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/abouts/_form.html.erb
<%= form_for(@about) do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :producer_name %><br />
    <%= f.text_field :producer_name %>
  </div>
  <div class="field">
    <%= f.label :producer_title %><br />
    <%= f.text_field :producer_title %>
  </div>
  <div class="field">
    <%= f.label :producer_email %><br />
    <%= f.text_field :producer_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing about</h1>

<%= render 'form' %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<h1>Listing abouts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Producer name</th>
    <th>Producer title</th>
    <th>Producer email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @abouts.each do |about| %>
  <tr>
    <td><%= about.title %></td>
    <td><%= about.description %></td>
    <td><%= about.producer_name %></td>
    <td><%= about.producer_title %></td>
    <td><%= about.producer_email %></td>
    <td><%= link_to 'Show', about %></td>
    <td><%= link_to 'Edit', edit_about_path(about) %></td>
    <td><%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New About', new_about_path %>

app/views/abouts/new.html.erb
<h1>New about</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @about.title %>
</p>

<p>
  <b>Description:</b>
  <%= @about.description %>
</p>

<p>
  <b>Producer name:</b>
  <%= @about.producer_name %>
</p>

<p>
  <b>Producer title:</b>
  <%= @about.producer_title %>
</p>

<p>
  <b>Producer email:</b>
  <%= @about.producer_email %>
</p>


<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>