config/routes.rb
Archispec::Application.routes.draw do
  

  
  resources :abouts

  resources :videos

  resources :locations

  resources :suppliers

  resources :programs

  resources :speakers

  devise_for :admins

mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' # Feel free to change '/admin' to any namespace you need.
root :to => 'archispec#home' #RAILS 3
  get "archispec/speakers"

  get "archispec/about_us"

  get "archispec/program"

  get "archispec/videos"

  get "archispec/partners"

  get "archispec/location"

  get "archispec/request_invite"

  get "archispec/home"

end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :description, :producer_email, :producer_name, :producer_title, :title
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :airpor_namet, :airport_description, :city, :description, :state, :title, :website, :zip
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :title
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  attr_accessible :bio, :name, :organization, :title
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :name
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :title, :vimeo_url
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/archispec_helper.rb
module ArchispecHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/speaker_helper.rb
module SpeakerHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :airpor_namet %><br />
    <%= f.text_field :airpor_namet %>
  </div>
  <div class="field">
    <%= f.label :airport_description %><br />
    <%= f.text_field :airport_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Website</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Airpor namet</th>
    <th>Airport description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.title %></td>
    <td><%= location.description %></td>
    <td><%= location.website %></td>
    <td><%= location.address %></td>
    <td><%= location.city %></td>
    <td><%= location.state %></td>
    <td><%= location.zip %></td>
    <td><%= location.airpor_namet %></td>
    <td><%= location.airport_description %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @location.title %>
</p>

<p>
  <b>Description:</b>
  <%= @location.description %>
</p>

<p>
  <b>Website:</b>
  <%= @location.website %>
</p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>State:</b>
  <%= @location.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @location.zip %>
</p>

<p>
  <b>Airpor namet:</b>
  <%= @location.airpor_namet %>
</p>

<p>
  <b>Airport description:</b>
  <%= @location.airport_description %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>